# Generated by Django 3.1.5 on 2021-04-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figure',
            old_name='photo',
            new_name='images',
        ),
    ]
